version: '3.8'

services:
  web:
    build: .
    ports:
      - '5000:5000'
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: unless-stopped


  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    depends_on:
      - web
    restart: unless-stopped
